config/routes.rb
Rails.application.routes.draw do
  resources :articles
  get 'groups/new'

  get 'sessions/new'

  get 'tests/new'

  get 'users/new'

  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'teams' => 'form_teams#index'
  get 'apply_teams' => 'form_teams#apply'
  get 'join_teams' => 'form_teams#join'
  get 'accpet_menber' => 'form_teams#accpet'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :groups
  resources :menbers
  get 'apply_merge_teams' => 'relationships#apply'
  get 'accpet_merge_teams' => 'relationships#accpet'

end

app/models/group.rb
class Group < ActiveRecord::Base

    has_many :menbers, dependent: :destroy
    has_many :articles, dependent: :destroy
    has_many :active_relationships, class_name: "Relationship",
                            foreign_key: "follower_id",
                            dependent: :destroy
    has_many :following, through: :active_relationships, source: :followed
    has_many :passive_relationships, class_name: "Relationship",
                            foreign_key: "followed_id",
                            dependent: :destroy
    has_many :followers, through: :passive_relationships, source: :follower
    validates :name, presence: true, length: { maximum: 50 }, 
                     uniqueness: { case_sensitive: false }
    validates :ccode, presence: true, length: { maximum: 50 }
    validates :ltnum, presence: true

    def follow(other_group)
        active_relationships.create(followed_id: other_group.id)
    end
    # 取消和另一组组合
    def unfollow(other_group)
        active_relationships.find_by(followed_id: other_group.id).destroy
    end
    # 如果当前发送了组合申请，则返回true
    def following?(other_group)
        following.include?(other_group)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group= Group.new
  end
  
  def index
    @groups = Group.where('name LIKE ?',  "%#{params[:search]}%")
                    .paginate :page => params[:page],
                              :per_page => 10
                              # :conditions => ["name like ?", "%#{params[:search]}%"]
    @allgroups = Group.all
  end
  
  def create
    @group = Group.new(group_params)
    @group.nownum = 1;
  #  puts "ooooooooo"
  #  puts current_user.name
  #  puts current_user
    if @group.save
       @menber = Menber.new(authority:1,status:1,
          user_id:current_user.id,group_id:@group.id)
       @menber.save
      flash[:success] = "队伍创建成功"
      redirect_to @group
    else
      render 'new'
    end
  end
  
  def show
    @group = Group.find(params[:id])
    @re_groups = Group.where('ccode = ? and name !=? and nownum <= ?', 
                            @group.ccode, @group.name, @group.ltnum - @group.nownum).order("nownum DESC").limit(6)
                 #           .paginate :page => params[:page],
                  #          :per_page => 5
    
    #@re_groups =  @re_groups[2..10]
  end
  
  def destroy
    Group.find(params[:id]).destroy
    flash[:success] = "Group deleted"
    redirect_to groups_path
  end 
  
  private
  
    def group_params
      params.require(:group).permit(:name, :ccode, :ltnum, :introduce)
    end
  
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/index.html.erb
<% provide(:title, "所有队伍") %>

<h1>所有队伍 </h1> <h2>(总数：<%= @allgroups.count %>)</h2>

<%= form_tag groups_path, :method => :get,  :class =>'form-inline' do -%>
   <%=text_field_tag "search", params[:search], :class => 'form-control' %>
   <button type="submit" class="btn btn-default">查找小组</button>
<% end -%>


<table class="table table-striped">
     <tr>
         <td>队伍名 </td>
         <td>组队人数</td>
         <td>课程名</td>
         <td>队伍简介</td>
         <td>操作</td>
     </tr>

    <% @groups.each do |group| %>
         <tr>
             <td><%= group.name %></td>
             <td><%= count_menber(group.menbers) %>/<%= group.ltnum %></td>
             <td><%= group.ccode %></td>
             <td><%= group.introduce %></td>
             <td> <% if current_user.admin? %>
                <%= link_to "删除", group, method: :delete,
                data: { confirm: "You sure?" } %>
                <% end %>
            </td>
            
         </tr>
         
    <% end %>
    
</table>
<%= will_paginate %>

app/views/groups/new.html.erb
<% provide(:title, 'found group') %>
<h1>创建队伍</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@group) do |f| %>
        
           <% if @group.errors.any? %>
                <div id="error_explanation">
                    <div class="alert alert-danger">
                        The form contains <%= pluralize(@group.errors.count, "error") %>.
                    </div>
                <ul>
                <% @group.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
                </ul>
                </div>
            <% end %>

        
            <%= f.label "队伍名" %>
            <%= f.text_field :name, class: 'form-control' %>
            
            <%= f.label "课程名称" %>
            <%= f.text_field :ccode, class: 'form-control' %>
            
            <%= f.label "限制人数" %>
            <%= f.number_field :ltnum, class: 'form-control' %>
            
            <%= f.label "队伍简介" %>
            <%= f.text_field :introduce, class: 'form-control' %>

            <%= f.submit "创建队伍", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/groups/show.html.erb
<%= link_to '我的队伍', current_user %> > <%= @group.name %><br>
<h1><%= @group.name %></h1>

<div class="row">

<%
    @m1 = 0
    @m0 = 0
    @group.menbers.each do |m|
        if m.status ==1
            @m1+=1
        else
            @m0+=1
        end
    end
%>

<aside class="col-md-8">
    <h3>队伍成员(<%=  @m1
                  %>)<h3>
    <table class="table table-striped">
        <tr>
             <td>用户名</td>
             <td>学院</td>
             <td>邮箱</td>
             <td>电话</td>
             <td>是否队长</td>
        </tr>
        <% @group.menbers.each do |menber| %>
              <% if menber.status == 1 %>
              <tr>
                 <td><%= menber.user.name %></td>
                 <td><%= menber.user.academy %></td>
                 <td><%= menber.user.email %></td>
                 <td><%= menber.user.phone %></td>
                 <td><% if menber.authority == 1 %>
                     是
                 <% else%>
                     否
                 <% end%></td>
             </tr>
              <% end %>
        <% end %>
    </table>
</aside>
 <div class="col-md-4">
   <h3><%=@group.name%> 的文章(<%= @group.articles.count %>)<h3>
   <table class="table table-striped">
      <tr>
          <td>标题</td>
          <td colspan="3">操作</td>
      </tr>

        <% @group.articles.each do |article| %>
          <tr>
            <td><%= article.name %></td>
            <td><%= link_to '详细', article %></td>
            <td><%= link_to '编辑', edit_article_path(article) %></td>
            <td><%= link_to '删除', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            
          </tr>
        <% end %>
    </table>
    
    <br>
    
    <h2><%= link_to '新建文章', new_article_url(group_id:@group.id) %></h2>
 </div>
</div>

<% if leader?(@group) %>
<div class="row">
<hr style="height:1px;border:none;border-top:1px solid #555555;" />
<aside class="col-md-12">
    <h3>申请加入的成员(<%= @m0
                  %>)<h3>
    <table class="table table-striped">
        <tr>
             <td>用户名</td>
             <td>申请理由</td>
             <td>操作</td>
        </tr>
        <% @group.menbers.each do |menber| %>
             <% if menber.status == 0 %>
              <tr>
                 <td><%= menber.user.name %></td>
                 <td><%= menber.message %></td>
                 <td><%= link_to "接受",accpet_menber_url(group_id:@group.id,
                     user_id:current_user.id,
                     menber_id:menber.id),
                     data: { confirm: "You sure?" } %>
                 </td>
             </tr>
             <% end %>
        <% end %>
    </table>
</aside>

</div>

<div class="row">
<hr style="height:1px;border:none;border-top:1px solid #555555;" />
    <aside class="col-md-6">
    <h3>推荐合并的队伍(<%=  @re_groups.count %>)<h3>
    <table class="table table-striped">
         <tr>
             <td>队伍名</td>
             <td>组队人数</td>
             <td>课程编号</td>
             <td>队伍简介</td>
             <td>操作</td>
         </tr>
    
        <% @re_groups.each do |group2| %>
             <tr>
                 <td><%= group2.name %></td>
                 <td><%= group2.nownum %>/<%= group2.ltnum %></td>
                 <td><%= group2.ccode %></td>
                 <td><%= group2.introduce %></td>
                 <td> | <%= link_to "邀请合并", apply_merge_teams_url(follower_id: @group.id,
                         followed_id: group2.id),
                    data: { confirm: "You sure?" } %>
                </td>
                
             </tr>
             
        <% end %>
    </table>
    </aside>
    
    <div class="col-md-6">
    
         <h3>申请合并的队伍 (<%=@group.following.count%>) <h3>
         <table class="table table-striped">
             <tr> 
                 <td>队伍名</td>
                 <td>组队人数</td>
                  <td>操作</td>
             </tr>
             <% @group.following.each do |f| %>
                  <tr>
                     <td><%= f.name %></td>
                     <td><%= f.nownum %>/<%= f.ltnum %></td>
                     <td><%= link_to "删除","#",
                         data: { confirm: "You sure?" } %>
                     </td>
                     
                 </tr>
            <% end %>
        </table>
        <hr style="height:1px;border:none;border-top:1px dashed #0066CC;" />
         <h3>被邀请合并的队伍 (<%=@group.followers.count%>)<h3>
         <table class="table table-striped">
             <tr> 
                 <td>队伍名</td>
                 <td>组队人数</td>
                 <td>操作</td>
             </tr>
             <% @group.followers.each do |f| %>
                  <tr>
                     <td><%= f.name %></td>
                     <td><%= f.nownum %>/<%= f.ltnum %></td>
                     <td><%= link_to "接受",accpet_merge_teams_url(followed_id: @group.id,
                         follower_id: f.id),
                         data: { confirm: "You sure?" } %>
                     </td>
                 </tr>
            <% end %>
        </table>
    </div>
</div>
<% end %>