config/routes.rb
Rails.application.routes.draw do
  resources :articles
  get 'groups/new'

  get 'sessions/new'

  get 'tests/new'

  get 'users/new'

  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'teams' => 'form_teams#index'
  get 'apply_teams' => 'form_teams#apply'
  get 'join_teams' => 'form_teams#join'
  get 'accpet_menber' => 'form_teams#accpet'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :groups
  resources :menbers
  get 'apply_merge_teams' => 'relationships#apply'
  get 'accpet_merge_teams' => 'relationships#accpet'

end

app/controllers/form_teams_controller.rb
class FormTeamsController < ApplicationController
    def index
        @groups = Group.where('name LIKE ? and ccode LIKE ?',  
                        "%#{params[:search]}%","%#{params[:search2]}%")
                        .paginate :page => params[:page],
                                  :per_page => 10
                                 
    end
    
    def apply
       @menber = Menber.new(authority:0,status:0,
                 user_id:params[:user_id], group_id:params[:group_id]);
    end
    
    def join
    end
    
    def accpet
        
        @menber = Menber.find(params[:menber_id] )
        @group = Group.find(params[:group_id])
        @menber.status=1
        @menber.save
        redirect_to @group
    end
 
end

app/helpers/form_teams_helper.rb
module FormTeamsHelper
end

app/views/form_teams/apply.html.erb
<h1>申请加入队伍</h1>
<%= form_for(@menber) do |f| %>
 
    <%= f.label "简单自我介绍(重点说明在大作业中能负责部分)" %>
    <%= f.text_area :message, class: 'form-control', cols: "30", rows: "5" %>
    <%= f.hidden_field :group_id, value: @menber.group_id %>
    <%= f.hidden_field :user_id, value: @menber.user_id%>
    <%= f.hidden_field :authority, value: @menber.authority %>
    <%= f.hidden_field :status, value: @menber.status %>
    <%= f.submit "申请加入", class: "btn btn-primary" %>
<% end %>

app/views/form_teams/index.html.erb
<% provide(:title, "选择加入队伍") %>

<h1>选择加入队伍 </h1>

<%= form_tag teams_path, :method => :get,  :class =>'form-inline' do -%>

   队伍名:<%=text_field_tag "search", params[:search], :class => 'span2 form-control' %>
   课程名称:<%=text_field_tag "search2", params[:search2], :class => 'form-control' %>
   <button type="submit" class="btn btn-default">查找</button>
<% end -%>


<table class="table table-striped">
     <tr>
         <td>队伍名</td>
         <td>组队人数</td>
         <td>课程名称</td>
         <td>队伍简介</td>
         <% if logged_in? %>
         <td>操作</td>
         <% end %>
     </tr>
<ul>
    <% @groups.each do |group| %>
         <tr>
             <td><%= group.name %></td>
             <td><%= count_menber(group.menbers) %>/<%= group.ltnum %></td>
             <td><%= group.ccode %></td>
             <td><%= group.introduce %></td>
             <% if logged_in? %>
             <td>
                 <% if group.nownum != group.ltnum %>
                 <%= link_to "申请加入",apply_teams_url(group_id:group.id,
                 user_id:current_user.id),
                 data: { confirm: "You sure?" } %>
                 <% end %>
             </td>
             <% end %>
         </tr>
    <% end %>
</ul>
</table>
<%= will_paginate @groups%>

app/views/form_teams/join.html.erb
<h1>jion由</h1>