config/routes.rb
Rails.application.routes.draw do
  resources :articles
  get 'groups/new'

  get 'sessions/new'

  get 'tests/new'

  get 'users/new'

  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'teams' => 'form_teams#index'
  get 'apply_teams' => 'form_teams#apply'
  get 'join_teams' => 'form_teams#join'
  get 'accpet_menber' => 'form_teams#accpet'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :groups
  resources :menbers
  get 'apply_merge_teams' => 'relationships#apply'
  get 'accpet_merge_teams' => 'relationships#accpet'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
<!--The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
by <a href="http://www.michaelhartl.com/">Michael Hartl</a>-->
瞅你咋的小组倾情制作
</small>
<nav>
<ul>
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Contact", contact_path %></li>
<li><a href="#">News</a></li>
</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "国科大组队网", root_path, id: "logo" %>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "主页", root_path %></li>
               
                <% if logged_in? %>
                    <li><%= link_to "课程队伍", teams_path %></li>
                    <% if admin_in? %>
                    
                            <li><%= link_to "用户管理", users_path %></li>
                            <li><li><%= link_to "队伍管理", groups_path %></li></li>
                    <% end %>
                    <li><%= link_to "创建队伍", new_group_path %></li>
                    <li><%= link_to "我的队伍", current_user %></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            用户 <b class="caret"></b>
                        </a>
                        
                        <ul class="dropdown-menu">
                            
                            <li><li><%= link_to "设置个人信息", edit_user_path(current_user) %></li></li>
                            <li class="divider"></li>
                            <li>
                                <%= link_to "退出登录", logout_path, method: "delete" %>
                            </li>
                        </ul>
                    </li>
                <% else %>
                    <li><%= link_to "Log in", login_path %></li>
                <% end %>
                
                <li><%= link_to "帮助", help_path %></li>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= full_title(yield(:title)) %></title>
<%= stylesheet_link_tag 'application', media: 'all',
'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>